"""Identifiability-aware CROME certification primitives."""

from .decision import ModelInfeasibleError, decide_target
from .calibration import (
    BoundedDesignErrorCalibration,
    DesignErrorCalibration,
    LowerMassCalibration,
    OutcomeNoiseCalibration,
    calibrate_bounded_design_error,
    calibrate_gaussian_design_error,
    calibrate_gaussian_outcome_noise,
    calibrate_lower_mass,
)
from .overlap import (
    certificate_optimized_weights,
    certificate_radius,
    certify_overlap_target,
    target_direct_weights,
)
from .temporal import (
    certify_temporal_conditional,
    certify_temporal_design_known,
    certify_temporal_empirical,
    certify_temporal_gap_conditional,
)
from .verification import verify_proof
from .types import (
    AnchoredEnvelopeProof,
    CertificateScope,
    CertificateClaimType,
    CertificationMode,
    CromeDecision,
    DecisionStatus,
    FailureBudget,
    FailureBudgetLedger,
    FailureSemantics,
    ExactNullProof,
    LinearBoundProof,
    OperationalStatus,
    ProofVerification,
    ScalarBoundProof,
    SetSubtype,
    StructuralStatus,
    SupportGapProof,
    TargetCertificate,
    TargetInterval,
    TemporalBoundProof,
    TemporalDesignBoundProof,
)

__all__ = [
    "AnchoredEnvelopeProof",
    "CertificateScope",
    "CertificateClaimType",
    "BoundedDesignErrorCalibration",
    "CertificationMode",
    "CromeDecision",
    "DecisionStatus",
    "FailureBudget",
    "FailureBudgetLedger",
    "FailureSemantics",
    "ExactNullProof",
    "LinearBoundProof",
    "DesignErrorCalibration",
    "LowerMassCalibration",
    "ModelInfeasibleError",
    "OutcomeNoiseCalibration",
    "OperationalStatus",
    "ProofVerification",
    "ScalarBoundProof",
    "TargetCertificate",
    "TargetInterval",
    "SetSubtype",
    "StructuralStatus",
    "SupportGapProof",
    "TemporalBoundProof",
    "TemporalDesignBoundProof",
    "calibrate_bounded_design_error",
    "calibrate_gaussian_design_error",
    "calibrate_gaussian_outcome_noise",
    "calibrate_lower_mass",
    "certify_overlap_target",
    "certificate_optimized_weights",
    "certificate_radius",
    "certify_temporal_conditional",
    "certify_temporal_design_known",
    "certify_temporal_empirical",
    "certify_temporal_gap_conditional",
    "decide_target",
    "target_direct_weights",
    "verify_proof",
]
